services:
  mytodo:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: mytodocopy:dev
    container_name: mytodocopy_dev
    volumes:
      - ./:/app
    ports:
      - '4200:4200'
#       image : nom de l'image qu'on va créer, évite d'avoir des doublons d'images
#       container name : le nom du container

#       le volume c'est le lien symbolique entre l'ordinateur et le containeur, c'est une façon de faire, il y en a plusieurs
#       ~ ./:/app fait un mirroir
